# == In this configuration, you set up Alchemy's element layouts.
#
# For further information please see http://guides.alchemy-cms.com/stable/elements.html

- name: logo
  hint: true
  unique: true
  contents:
  - name: image
    type: EssencePicture
    hint: true

- name: tech_menu_one
  hint: true
  unique: true
  contents:
  - name: image
    type: EssencePicture
    hint: true

- name: section_one_tech_one
  hint: true
  unique: true
  contents:
    - name: image
      type: EssencePicture
      hint: true

- name: section_one_tech_two
  hint: true
  unique: true
  contents:
    - name: image
      type: EssencePicture
      hint: true

- name: section_one_tech_three
  hint: true
  unique: true
  contents:
    - name: image
      type: EssencePicture
      hint: true

- name: section_one
  hint: true
  unique: true
  nestable_elements:
  - section_one_tech_one
  - section_one_tech_two
  - section_one_tech_three