development: 
  cloud_name: <%= ENV['CLOUD_DEV_NAME']%>
  api_key: <%= ENV['CLOUD_DEV_API_KEY']%>
  api_secret: <%= ENV['CLOUD_DEV_API_SECRET']%>
  secure: true

production:
  cloud_name: <%= ENV['CLOUD_PROD_NAME']%>
  api_key: <%= ENV['CLOUD_PROD_API_KEY']%>
  api_secret: <%= ENV['CLOUD_PROD_API_SECRET']%>
  secure: true